BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `User` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`Name`	TEXT NOT NULL,
	`Email`	TEXT NOT NULL UNIQUE,
	`Username`	TEXT NOT NULL UNIQUE,
	`Password`	TEXT NOT NULL,
	`Type`	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS `TripReport` (
	`CommentId`	INTEGER,
	`Result`	INTEGER NOT NULL,
	FOREIGN KEY(`CommentId`) REFERENCES `Comment`(`Id`)
);
CREATE TABLE IF NOT EXISTS `Destination` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`Name`	TEXT NOT NULL,
	`Region`	TEXT,
	`EvGain`	INTEGER,
	`Distance`	REAL NOT NULL,
	`Coords`	TEXT,
	`EndCoords`	TEXT,
	`PDiff`	INTEGER NOT NULL,
	`TDiff`	INTEGER NOT NULL,
	`PeakEv`	INTEGER
);
CREATE TABLE IF NOT EXISTS `Comment` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`DestId`	INTEGER NOT NULL,
	`UserId`	INTEGER NOT NULL,
	`Time`	INTEGER NOT NULL,
	`Text`	TEXT NOT NULL,
	FOREIGN KEY(`DestId`) REFERENCES `Destination`(`Id`),
	FOREIGN KEY(`UserId`) REFERENCES `User`(`Id`)
);
CREATE TABLE IF NOT EXISTS `Admins` (
	`UserId`	INTEGER NOT NULL,
	`Region`	TEXT NOT NULL,
	FOREIGN KEY(`UserId`) REFERENCES `User`(`Id`)
);
COMMIT;
